language: php

sudo: required

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4

env:
  # plugin code
  global:
    PLUGIN_CODE=ProductPriority
  matrix:
      # for coverrage
      - ECCUBE_VERSION=master DB=pgsql USER=postgres DBNAME=myapp_test DBPASS=password DBUSER=postgres COVERRAGE=true
      # ec-cube master
      - ECCUBE_VERSION=master DB=mysql USER=root DBNAME=myapp_test DBPASS=' ' DBUSER=root
      - ECCUBE_VERSION=master DB=pgsql USER=postgres DBNAME=myapp_test DBPASS=password DBUSER=postgres
      - ECCUBE_VERSION=master DB=sqlite
      # ec-cube 3.0.13
      - ECCUBE_VERSION=3.0.13 DB=mysql USER=root DBNAME=myapp_test DBPASS=' ' DBUSER=root
      - ECCUBE_VERSION=3.0.13 DB=pgsql USER=postgres DBNAME=myapp_test DBPASS=password DBUSER=postgres
      - ECCUBE_VERSION=3.0.13 DB=sqlite

matrix:
  fast_finish: true
  include:
    - php: 5.3
      dist: precise
  exclude:
    - php: 7.1
      env: ECCUBE_VERSION=master DB=pgsql USER=postgres DBNAME=myapp_test DBPASS=password DBUSER=postgres COVERRAGE=true
    - php: 5.6
      env: ECCUBE_VERSION=master DB=pgsql USER=postgres DBNAME=myapp_test DBPASS=password DBUSER=postgres COVERRAGE=true
    - php: 5.5
      env: ECCUBE_VERSION=master DB=pgsql USER=postgres DBNAME=myapp_test DBPASS=password DBUSER=postgres COVERRAGE=true
    - php: 5.4
      env: ECCUBE_VERSION=master DB=pgsql USER=postgres DBNAME=myapp_test DBPASS=password DBUSER=postgres COVERRAGE=true
    - php: 5.3
      env: ECCUBE_VERSION=master DB=pgsql USER=postgres DBNAME=myapp_test DBPASS=password DBUSER=postgres COVERRAGE=true
  allow_failures:
    - php: 7.0
      env: ECCUBE_VERSION=master DB=pgsql USER=postgres DBNAME=myapp_test DBPASS=password DBUSER=postgres COVERRAGE=true
    - env: ECCUBE_VERSION=master DB=sqlite
    - env: ECCUBE_VERSION=3.0.13 DB=sqlite

before_script:
  # archive plugin
  - tar cvzf ${HOME}/${PLUGIN_CODE}.tar.gz ./*
  # clone ec-cube
  - git clone https://github.com/EC-CUBE/ec-cube.git
  - cd ec-cube
  # checkout version
  - sh -c "if [ ! '${ECCUBE_VERSION}' = 'master' ]; then  git checkout -b ${ECCUBE_VERSION} refs/tags/${ECCUBE_VERSION}; fi"
  # update composer
  - composer selfupdate
  - composer install --dev --no-interaction -o
  # install ec-cube
  - php eccube_install.php $DB none -V
  # install plugin
  - php app/console plugin:develop install --path=${HOME}/${PLUGIN_CODE}.tar.gz
  # enable plugin
  - php app/console plugin:develop enable --code=${PLUGIN_CODE}

script:
  # exec phpunit on ec-cube
  - if [[ ! $COVERRAGE = 'true' ]]; then phpunit app/Plugin/${PLUGIN_CODE}/Tests; fi
  - if [[ $COVERRAGE = 'true' ]]; then ./vendor/bin/phpunit -c app/Plugin/${PLUGIN_CODE}/phpunit.xml.dist --coverage-clover=coverage.clover; fi

after_script:
  # disable plugin
  - php app/console plugin:develop disable --code=${PLUGIN_CODE} || exit 1
  # uninstall plugin
  - php app/console plugin:develop uninstall --code=${PLUGIN_CODE} || exit 1
  # re install plugin
  - php app/console plugin:develop install --code=${PLUGIN_CODE} || exit 1
  # re enable plugin
  - php app/console plugin:develop enable --code=${PLUGIN_CODE} || exit 1

after_success:
  # for coveralls
  - if [[ $COVERRAGE = 'true' ]]; then php vendor/bin/coveralls -v -x coverage.clover; fi
